name: dakanji
version: git
summary: Draw a kanji with your mouse and open it in your dictionary of choice.
description: |
  Did you ever try to read a Japanese text but did not know how to read some Kanji? This app can help you with exactly that.
  Draw a Kanji and the app will convert it to a digital character.
  You can than open that character in a dictionary of your choice or use it somewhere else.

  This app works completely offline and no internet connection is needed for recognizing the characters.

  Features:
    * Recognize Kanji characters offline
    * Use a web dictionary to translate characters
base: core18
confinement: devmode


parts:
  test-offlineimap:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six

apps:
  dakanji:
    command: bin/dakanji